//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Bonitet.CRM.CRMServiceProxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CRMServiceProxySoap", Namespace="http://eboniteti.mk/")]
    public partial class CRMServiceProxy : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResultsForReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CRMServiceProxy() {
            this.Url = global::Bonitet.CRM.Properties.Settings.Default.Bonitet_CRM_CRMServiceProxy_CRMServiceProxy;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetResultsCompletedEventHandler GetResultsCompleted;
        
        /// <remarks/>
        public event GetResultsForReportCompletedEventHandler GetResultsForReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eboniteti.mk/GetResults", RequestNamespace="http://eboniteti.mk/", ResponseNamespace="http://eboniteti.mk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetResults(string embs, int UserID, string ticket) {
            object[] results = this.Invoke("GetResults", new object[] {
                        embs,
                        UserID,
                        ticket});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetResultsAsync(string embs, int UserID, string ticket) {
            this.GetResultsAsync(embs, UserID, ticket, null);
        }
        
        /// <remarks/>
        public void GetResultsAsync(string embs, int UserID, string ticket, object userState) {
            if ((this.GetResultsOperationCompleted == null)) {
                this.GetResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResultsOperationCompleted);
            }
            this.InvokeAsync("GetResults", new object[] {
                        embs,
                        UserID,
                        ticket}, this.GetResultsOperationCompleted, userState);
        }
        
        private void OnGetResultsOperationCompleted(object arg) {
            if ((this.GetResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResultsCompleted(this, new GetResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eboniteti.mk/GetResultsForReport", RequestNamespace="http://eboniteti.mk/", ResponseNamespace="http://eboniteti.mk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetResultsForReport(string embs, int year, bool force_crm) {
            object[] results = this.Invoke("GetResultsForReport", new object[] {
                        embs,
                        year,
                        force_crm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetResultsForReportAsync(string embs, int year, bool force_crm) {
            this.GetResultsForReportAsync(embs, year, force_crm, null);
        }
        
        /// <remarks/>
        public void GetResultsForReportAsync(string embs, int year, bool force_crm, object userState) {
            if ((this.GetResultsForReportOperationCompleted == null)) {
                this.GetResultsForReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResultsForReportOperationCompleted);
            }
            this.InvokeAsync("GetResultsForReport", new object[] {
                        embs,
                        year,
                        force_crm}, this.GetResultsForReportOperationCompleted, userState);
        }
        
        private void OnGetResultsForReportOperationCompleted(object arg) {
            if ((this.GetResultsForReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResultsForReportCompleted(this, new GetResultsForReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetResultsCompletedEventHandler(object sender, GetResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetResultsForReportCompletedEventHandler(object sender, GetResultsForReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResultsForReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResultsForReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591