//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonitet.ConsoleTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://e-test.crm.com.mk/XWSS/", ConfigurationName="ServiceReference1.XmlWebServiceSoap")]
    public interface XmlWebServiceSoap {
        
        // CODEGEN: Generating message contract since message ProcessRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://e-test.crm.com.mk/XWSS/ProcessRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bonitet.ConsoleTest.ServiceReference1.ProcessRequestResponse ProcessRequest(Bonitet.ConsoleTest.ServiceReference1.ProcessRequestRequest request);
        
        // CODEGEN: Generating message contract since message ProcessSignedRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://e-test.crm.com.mk/XWSS/ProcessSignedRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bonitet.ConsoleTest.ServiceReference1.ProcessSignedRequestResponse ProcessSignedRequest(Bonitet.ConsoleTest.ServiceReference1.ProcessSignedRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://e-test.crm.com.mk/XWSS/")]
    public partial class XmlSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessRequest", WrapperNamespace="https://e-test.crm.com.mk/XWSS/", IsWrapped=true)]
    public partial class ProcessRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://e-test.crm.com.mk/XWSS/")]
        public Bonitet.ConsoleTest.ServiceReference1.XmlSoapHeader XmlSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://e-test.crm.com.mk/XWSS/", Order=0)]
        public string parameters;
        
        public ProcessRequestRequest() {
        }
        
        public ProcessRequestRequest(Bonitet.ConsoleTest.ServiceReference1.XmlSoapHeader XmlSoapHeader, string parameters) {
            this.XmlSoapHeader = XmlSoapHeader;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessRequestResponse", WrapperNamespace="https://e-test.crm.com.mk/XWSS/", IsWrapped=true)]
    public partial class ProcessRequestResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://e-test.crm.com.mk/XWSS/")]
        public Bonitet.ConsoleTest.ServiceReference1.XmlSoapHeader XmlSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://e-test.crm.com.mk/XWSS/", Order=0)]
        public string ProcessRequestResult;
        
        public ProcessRequestResponse() {
        }
        
        public ProcessRequestResponse(Bonitet.ConsoleTest.ServiceReference1.XmlSoapHeader XmlSoapHeader, string ProcessRequestResult) {
            this.XmlSoapHeader = XmlSoapHeader;
            this.ProcessRequestResult = ProcessRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessSignedRequest", WrapperNamespace="https://e-test.crm.com.mk/XWSS/", IsWrapped=true)]
    public partial class ProcessSignedRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://e-test.crm.com.mk/XWSS/")]
        public Bonitet.ConsoleTest.ServiceReference1.XmlSoapHeader XmlSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://e-test.crm.com.mk/XWSS/", Order=0)]
        public string parameters;
        
        public ProcessSignedRequestRequest() {
        }
        
        public ProcessSignedRequestRequest(Bonitet.ConsoleTest.ServiceReference1.XmlSoapHeader XmlSoapHeader, string parameters) {
            this.XmlSoapHeader = XmlSoapHeader;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessSignedRequestResponse", WrapperNamespace="https://e-test.crm.com.mk/XWSS/", IsWrapped=true)]
    public partial class ProcessSignedRequestResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://e-test.crm.com.mk/XWSS/")]
        public Bonitet.ConsoleTest.ServiceReference1.XmlSoapHeader XmlSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://e-test.crm.com.mk/XWSS/", Order=0)]
        public string ProcessSignedRequestResult;
        
        public ProcessSignedRequestResponse() {
        }
        
        public ProcessSignedRequestResponse(Bonitet.ConsoleTest.ServiceReference1.XmlSoapHeader XmlSoapHeader, string ProcessSignedRequestResult) {
            this.XmlSoapHeader = XmlSoapHeader;
            this.ProcessSignedRequestResult = ProcessSignedRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XmlWebServiceSoapChannel : Bonitet.ConsoleTest.ServiceReference1.XmlWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XmlWebServiceSoapClient : System.ServiceModel.ClientBase<Bonitet.ConsoleTest.ServiceReference1.XmlWebServiceSoap>, Bonitet.ConsoleTest.ServiceReference1.XmlWebServiceSoap {
        
        public XmlWebServiceSoapClient() {
        }
        
        public XmlWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XmlWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonitet.ConsoleTest.ServiceReference1.ProcessRequestResponse Bonitet.ConsoleTest.ServiceReference1.XmlWebServiceSoap.ProcessRequest(Bonitet.ConsoleTest.ServiceReference1.ProcessRequestRequest request) {
            return base.Channel.ProcessRequest(request);
        }
        
        public string ProcessRequest(ref Bonitet.ConsoleTest.ServiceReference1.XmlSoapHeader XmlSoapHeader, string parameters) {
            Bonitet.ConsoleTest.ServiceReference1.ProcessRequestRequest inValue = new Bonitet.ConsoleTest.ServiceReference1.ProcessRequestRequest();
            inValue.XmlSoapHeader = XmlSoapHeader;
            inValue.parameters = parameters;
            Bonitet.ConsoleTest.ServiceReference1.ProcessRequestResponse retVal = ((Bonitet.ConsoleTest.ServiceReference1.XmlWebServiceSoap)(this)).ProcessRequest(inValue);
            XmlSoapHeader = retVal.XmlSoapHeader;
            return retVal.ProcessRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonitet.ConsoleTest.ServiceReference1.ProcessSignedRequestResponse Bonitet.ConsoleTest.ServiceReference1.XmlWebServiceSoap.ProcessSignedRequest(Bonitet.ConsoleTest.ServiceReference1.ProcessSignedRequestRequest request) {
            return base.Channel.ProcessSignedRequest(request);
        }
        
        public string ProcessSignedRequest(ref Bonitet.ConsoleTest.ServiceReference1.XmlSoapHeader XmlSoapHeader, string parameters) {
            Bonitet.ConsoleTest.ServiceReference1.ProcessSignedRequestRequest inValue = new Bonitet.ConsoleTest.ServiceReference1.ProcessSignedRequestRequest();
            inValue.XmlSoapHeader = XmlSoapHeader;
            inValue.parameters = parameters;
            Bonitet.ConsoleTest.ServiceReference1.ProcessSignedRequestResponse retVal = ((Bonitet.ConsoleTest.ServiceReference1.XmlWebServiceSoap)(this)).ProcessSignedRequest(inValue);
            XmlSoapHeader = retVal.XmlSoapHeader;
            return retVal.ProcessSignedRequestResult;
        }
    }
}
